services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mounts your local project to the container
      - /app/node_modules  # Prevents overwriting node_modules inside the container
    environment:
      - NODE_ENV=development
    command: ["npx", "nodemon", "-L", "server.js"]  # -L ensures nodemon detects changes in Docker
